### ISSUE TITLE
Better Role organization, allow self assignment through bot

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-wunderbot#134]
Starting talking to MSFT about a server role re-design. Idea is to use roles more effectively and clean up the discord experience for new users. By default, users would have access to the main LBRY channels (general/help/verification) and then they would request roles (through the addroles bot) for things like mining, trading, nsfw. Probably have a "community" role too which just unlocks them all  or something. 

@MSFTserver can you take the lead on writing up a design spec / initial implementation for something like this?

**Comment by MSFTserver** [comment]
yup I can start on that this week, was gonna work on it last time we discussed it but some family stuff came up

**Comment by Coolguy3289** [comment]
All that should need done is to add the roles in the discord, then add the names to the wunderbot config

**Comment by MSFTserver** [comment]
and messing with all permissions, reorganizing channels, this going to go along with the full server redesign

**Comment by Coolguy3289** [comment]
I wouldn't even go that far, but regardless, Either Brazen needs to work on this tightly with @MSFTserver, or @MSFTserver will need elevated permissions to get it done.

**Comment by Coolguy3289** [comment]
The nice thing about Discord is the categories, which can streamline most of the channels, minus a few exceptions.

**Comment by Coolguy3289** [comment]
# List of possible Roles in the discord:
* LBRY Team
* LBRY Design Team
* Senior Assistant
* Assistant
* Junior Assistant
* Volunteer Assistant
* LBRY Assistant
The Above would be able to see into All channels that exist except for obvious appropriate ones (E.g TeamChat).
* LBRY F&F
* Moderator Team
* Support Team
* Community Dev Team
* Contest Judge (Can be removed imo)
* LBRY Early Tester
* Bounty Seekers
* Mining Pool Operator
* Recognized Publisher
* Tickety
* SBot
* Wunderbot
* Tipbot
The above roles are pretty static, and are assigned by the Team. Below is all of the User's roles that they can add to themselves.
* NSFW (Access to random-nsfw, and Drugs Channel)
* Market and Trading ( Access to Market and Trading Channel)
* Miner ( Access to Mining Channel)
* Chatter ( Access to all other Off-Topic Channels minus bot-sandbox)
The below Role would be the base role assigned to a member when either they give themselves one of the above mentioned roles, or they add this role directly
* Member (Access to LBRY Chat Channels, Community Channels, and Contributing to LBRY channels)

# Channel Structure
* As I tried to make apparent above, depending on the role you have, will determine what channels you see. As a new member just joining the server, you will have no roles, and will only be able to see the channels in Information/Announcements and the Support channels.
* To see most of the other channels, users will have to have the `Member` Role, which will grant access to the channels in the categories above. 
* To see other, more specialized channels, they just add other roles that would interest them.

# How to accomplish making users aware of this
There are a couple options here:
* One option is to change the welcome message sent by Wunderbot to explain how to see other channels, and where to start , this can be included in my upcoming update to how the welcome message works.
* Another, is to have a dedicated channel for newcomers where wunderbot will post a generic message there to explain how to get yourself started in the discord. This way, if a user doesn't see it the first time, they'll see it a dozen times. Set it up so that until a user has the Member role, the newcomer chat is the only where they can type, and once they add themselves to the Member role, they can no longer see that chat and won't get spammed by Wunderbot.
*If anyone has another solution, please feel free to comment*
*If I missed something, let me know, and I'll add it!*

**Comment by Smurphonomics** [comment]
While most names are suffice, I feel **Junior Assistant** should be changed. Maybe **Trainee Assistant**?

Some Junior Assistant are 30+ in age.

**Comment by filipnyquist** [comment]
A rework of the assistant roles is on the way

**Comment by tzarebczan** [comment]
@Coolguy3289 I also like your idea about having a new member channel - I think this is how r/cryptocurrency Discord was setup  - the users had to agree to something before continuing. But in that case it was a private channel for the user as opposed to a public one which it sounds like you are proposing.  Can you take a look into the private option and see how r/cryptocurrency (https://discord.gg/d7MwNgE) works  ?

**Comment by Coolguy3289** [comment]
#153 Has added these features into the bot.

**Comment by Coolguy3289** [comment]
I looked at the CryptoCurrency discord, they just have a 5 min. Wait before being able do to anything, rather than physically agreeing to something via chat.

**Comment by tzarebczan** [comment]
So this is the plan:
#welcome-to-lbry channel will have welcome messages and instructions on how to self assign roles. Users without a role will have access to #welcome-to-lbry, #role-assign, Information & Updates and Support categories. Other areas/channels will have access based on self assigned roles. All the self assigned roles will be the same color (yellow?). 

New roles to be created and their assignments (Thanks to @Coolguy3289 for doing the thinking already here). I'm not convinced on the role names...not sure if it should just be NSFW, or NSFW Chat. @Smurphonomics  / @jsigwart any thoughts? 

LBRYian - access to LBRY Chat, Contributing to LBRY and Community categories

NSFW Chat  - access to #Random-NSFW & #Drugs channels

Off-Topic Chat - access to Off Topic Category

Market Chat - access to #market-and-trading

Mining Chat - access to #mining

@Smurphonomics can you start working on the welcome message? Feel free to start off what the welcome message from wunderbot (I just sent you one). We can clean that up later, or make it more specific for certain messages.  It should include instructions on how to go to #role-assign and assign a role, with a listing of roles available and what they give access to (spell out NSFW). 

Last, we'll need to create a new server link to the #welcome-to-lbry channel and get that updated on chat.lbry.io.

**Comment by Coolguy3289** [comment]
The preliminary setup for this change has been completed. All Categories have the necessary roles in place.

**Comment by Coolguy3289** [comment]
I will start adjusting the config for the wunderbot

**Comment by Coolguy3289** [comment]
#159 Updated the roles in the default config. Adjusting Production config to match.

**Comment by tzarebczan** [comment]
@jsigwart suggested to have an international role which would give access to international channels.

It just occurred to me it might be a good idea to have a dev role too, what do you guys think?

**Comment by jsigwart** [comment]
Absolutely! I think that's a great idea. I think that would help keep the support requests out of the dev channels.

**Comment by tzarebczan** [comment]
Other new roles:
Developer -> access to #dev, #dev-random, #dev-ux, #design in Contributing category
International -> access to International (new category with #en-francais)

I've moved Ideas/Feedback to Support

@julie are you okay with this? Should we shift anything else around?

**Comment by Coolguy3289** [comment]
I've moved #en-francais to the new International Category. Created the Dev and International roles, and changed the access roles on Contributing to LBRY to accurately reflect the new changes.

**Comment by Coolguy3289** [comment]
This is now live. Can this issue be closed @tzarebczan ?

**Comment by tzarebczan** [comment]
Yup, thanks!
