### ISSUE TITLE
Add modular welcome message

### ISSUE THREAD

**Issue by Coolguy3289** [lbryio/lbry-wunderbot#141]
I am currently working on adding the ability for the welcome function to send messages about LBRY based off of a reaction from the user it has sent a message to. I have gotten this to work in the `!welcome @user` command, however I can't seem to get the FirstJoin event to fire correctly because the function needs to be async to use the `await` function. Making Progress, but this is mostly to inform of my current progress, and track while I fix these issues.

**Comment by tzarebczan** [comment]
Do we still want to do this with the role re-org/ welcome channel? My guess is no, unless you are really close to a solution.

**Comment by Coolguy3289** [comment]
I'm not. Electron was going to take a look into it, but hasn't got back to me. I'd say we can table the Welcome Message function for now.

**Comment by tzarebczan** [comment]
We don't need the bot messaging to work on the join event anymore since we'll have the message posted in #welcome-to-lbry . I'm not sure how/where we want to re-introduce the bot messaging system yet ...maybe we can have an alias for welcome that the user can run themselves to interact with the bot..i.e. !learnmore or something.

**Comment by Coolguy3289** [comment]
Closing till Further notice.
