### ISSUE TITLE
Include fee costs 

### ISSUE THREAD

**Issue by danger89** [lbryio/lbry-wunderbot#255]
Hi,

I think it's better to include the fee costs when giving somebody a tip with the bot. 

Currently, when yiu got tipped by 50 lbc, you actually receive 49,99743 lbc because of the fee costs that get subtracted.

My proposal would be to include it upfront, so the person who receives the fee actually get 50 lbc in this example. Simular to the lbry app. 

Thanks! 

Regards, 
Melroy van den Berg

**Comment by tzarebczan** [comment]
Whoops, not sure why I closed this. We actually do cover the fees, but when you withdraw your entire balance, it goes into the negative, which then becomes an issue when you receive a some more. 

I'd say we should prevent the balances from going below zero, and we should be fine. 

This whole process will need to be re-written since it currently uses the accounts feature of Bitcoin that's been recently deprecated.

**Comment by Coolguy3289** [comment]
This should be moved to the tipbot repo. Closing for now, but agree with the issue as a whole.

**Comment by danger89** [comment]
Owh, do you open a new Issue or?

**Comment by tzarebczan** [comment]
I think it would make sense to do this when we re-write the tipbot to support the non-account based method of tracking balances.
